import { HMRouterMgr } from "@hadss/hmrouter"
import { MyBricks } from "./utils/types"
import { Subject, emit } from "./utils/mybricks"
$r('app.api.import')

type Callback<P, R> = (value: P) => R

class Api {
  private callbacks: Map<string, Callback<MyBricks.EventValue, MyBricks.EventValue>> = new Map()

  open(value?: MyBricks.EventValue) {
    HMRouterMgr.push({
      pageUrl: PAGE_URL,
    });

    $r('app.api.open')
  }

  on<P, R>(key: string, callback: Callback<P, R>) {
    this.callbacks.set(key, callback)
  }

  emit(key: string, value: MyBricks.EventValue): Subject {
    const callback = this.callbacks.get(key)

    return emit(callback, value)
  }
}

export const PAGE_URL = $r('app.config.pageUrl')

export default new Api()
